language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t felipe/docker-react -f Dockerfile.dev .

script:
    - docker run felipe/docker-react npm run test -- --coverage